version: "3.8"
services:
  logstash:
    image: logstash:7.9.3
    networks:
      - elasticsearch_network
  
  cerebro:
    image: lmenezes/cerebro
    container_name: cerebro-elasticsearch
    ports:
      - 9000:9000
    # environment:
      #  CEREBRO_PORT: 8080
    networks:
      - elasticsearch_network
    
  elasticsearch:
    image: elasticsearch:7.9.3
    container_name: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      discovery.type: single-node
    networks:
      - elasticsearch_network

networks:
  elasticsearch_network: